apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3001  # Matches the containerPort
  type: LoadBalancer  # Change to LoadBalancer if external access is needed

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 145048992629.dkr.ecr.us-east-1.amazonaws.com/sd4413-practical-devops:backend-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
